### PR TITLE
Update exercise2.adoc

### PR DESCRIPTION
**Pull request by medberry**
image references need to refer to images subdirectory.

### CODE REVIEW

**Comment by cigamit** [comment]
I will have to see how the AsciiDoc compiler handles this first, since we are converting these from Asciidoc to HTML on the fly.

**Comment by medberry** [comment]
Ah, I was just trying to utilize the adoc files in github directly. So my usecase my not be intended. Where does the provisioner put the html generated docs for use in a class? Does it leverage some of the vars/main.yml like linklight does with the -e @custom.yml ?

**Comment by cigamit** [comment]
It creates a complete docs VM.  This VM also houses the decks, and the user registration page (student and workstation assignment).

**Comment by cigamit** [comment]
Ok, I fixed this myself in all the exercises.  We had to remove the entry from header first that was setting the image directory.  They should compile fine now in asciidoc while also being viewable in Github.

**Pull request closed without merging**
