### PR TITLE
add support for providing tower license as a variable (tower_license)

### PR DESCRIPTION
**Pull request by oatakan**

### CODE REVIEW

**Comment by cigamit** [comment]
May have to revert this one for the time being, if you provide the license via file, you still get this error during provisioning

```
TASK [ansible-tower : Post license key] ***********************************************************************************************************************************************************************
fatal: [s1-tower]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'tower_license' is undefined
```

**Comment by cigamit** [comment]
Another thing to note, if the license is provided via variable, it is not checked for EULA_ACCEPTED and thus the playbook will fail if its not there

**Comment by cigamit** [comment]
The problem with this PR, is that the variable is set via set_fact, which is basically another name for "set_hostvar".  We are utilizing the localhost at the time, so the tower_license variable itself is not available to the tower hosts when we get down to the later portion of the playbook.  An option would be to set a hostvar for each tower server or to rerun the check_setup role for each tower server (time consuming, and would have to modify the role to delegate local).  Option 1 is the best, and I will probably add that in.

**Comment by oatakan** [comment]
good points. agree on Option 1.

**Pull request merged**
